import assert from "node:assert/strict";
import { once } from "node:events";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { createConsole, createRun, Port } from "@evolu/common";
import { installPolyfills } from "@evolu/common/polyfills";
import { createRelayDeps } from "@evolu/nodejs";
import { WebSocket } from "ws";
import Database from "better-sqlite3";
import { setTimeout as sleep } from "node:timers/promises";
import {
  createProtocolMessageBuffer, MessageType, SubscriptionFlags,
} from "@evolu/common/local-first";
import { compactOwner } from "../dist/lib/compact-owner.js";

import { createReplayProtectedRelay } from "../dist/lib/replay-protected-relay.js";

installPolyfills();

test("replay-protected relay starts, accepts WebSockets, and shuts down", async () => {
  const dataDir = mkdtempSync(join(tmpdir(), "replay-protected-relay-"));
  const previousCwd = process.cwd();
  const console = createConsole({ level: "silent" });
  const logger = {
    console,
    emit: () => {},
    getCurrentConnections: () => 0,
    setOwnerCallback: () => {},
  };
  const run = createRun({ ...createRelayDeps(), console, logger });
  let relay;

  try {
    process.chdir(dataDir);
    const result = await run.abortable(
      createReplayProtectedRelay({
        port: Port.orThrow(0),
        isOwnerWithinQuota: () => true,
      }),
    );
    assert.equal(result.ok, true, "relay should start");
    relay = result.value;
    assert.ok(relay.port > 0, "relay should expose its bound ephemeral port");

    const socket = new WebSocket(`ws://127.0.0.1:${relay.port}`);
    await once(socket, "open");
    const closed = once(socket, "close");
    socket.close();
    await closed;
  } finally {
    if (relay) await relay[Symbol.asyncDispose]();
    await run[Symbol.asyncDispose]();
    process.chdir(previousCwd);
    rmSync(dataDir, { recursive: true, force: true });
  }
});

async function withRelay(callback, options = {}) {
  const dataDir = mkdtempSync(join(tmpdir(), "relay-regression-"));
  const previousCwd = process.cwd();
  const console = createConsole({ level: "silent" });
  const logger = { console, emit() {}, getCurrentConnections() { return 0; }, setOwnerCallback() {} };
  const run = createRun({ ...createRelayDeps(), console, logger });
  const sockets = [];
  let relay;
  try {
    process.chdir(dataDir);
    const result = await run.abortable(createReplayProtectedRelay({
      port: Port.orThrow(0), isOwnerWithinQuota: () => true, ...options,
    }));
    assert.equal(result.ok, true);
    relay = result.value;
    const connect = async (config) => {
      const socket = new WebSocket(`ws://127.0.0.1:${relay.port}`, config);
      sockets.push(socket);
      await once(socket, "open", { signal: AbortSignal.timeout(3000) });
      return socket;
    };
    await callback({ connect, dataDir, relay, run });
  } finally {
    for (const socket of sockets) socket.terminate();
    if (relay) await relay[Symbol.asyncDispose]();
    await run[Symbol.asyncDispose]();
    process.chdir(previousCwd);
    rmSync(dataDir, { recursive: true, force: true });
  }
}

const ownerBytes = Buffer.alloc(16, 1);
const ownerId = ownerBytes.toString("base64url");
const writeKey = Buffer.alloc(16, 2);
const oldMessage = { timestamp: { millis: 1000, counter: 0, nodeId: "0011223344556677" }, change: Buffer.alloc(80, 3) };
const freshMessage = { timestamp: { millis: 2000, counter: 0, nodeId: "0011223344556677" }, change: Buffer.alloc(17, 4) };
function request(messages = [], subscribe = false) {
  const frame = createProtocolMessageBuffer(ownerId, {
    messageType: MessageType.Request, writeKey,
    subscriptionFlag: subscribe ? SubscriptionFlags.Subscribe : SubscriptionFlags.None,
  });
  for (const message of messages) frame.addMessage(message);
  return frame.unwrap();
}
async function send(socket, frame) {
  const response = once(socket, "message", { signal: AbortSignal.timeout(3000) });
  socket.send(frame);
  return (await response)[0];
}

test("Evolu 8.7 wire fixture is persisted with the original owner key", async () => {
  // Generated by @evolu/common 8.7.0, used by the existing GetBased browser.
  const fixture = Buffer.from("01010101010101010101010101010101010001020202020202020202020202020202020101e807000100112233445566770150" + "03".repeat(80), "hex");
  await withRelay(async ({ connect }) => {
    await send(await connect(), fixture);
    const db = new Database("evolu-relay.db", { readonly: true });
    try {
      assert.deepEqual(db.prepare("SELECT writeKey FROM evolu_writeKey").get().writeKey, writeKey);
      assert.equal(db.prepare("SELECT storedBytes FROM evolu_usage").get().storedBytes, 80);
    } finally { db.close(); }
  });
});

test("compaction filters replay-only and mixed broadcasts and still sends fresh writes", async () => {
  await withRelay(async ({ connect }) => {
    const writer = await connect();
    await send(writer, request([oldMessage]));
    const db = new Database("evolu-relay.db");
    try {
      compactOwner(db, ownerBytes);
      const subscriber = await connect();
      await send(subscriber, request([], true));
      const broadcasts = [];
      subscriber.on("message", frame => broadcasts.push(frame));
      await send(writer, request([oldMessage]));
      await sleep(40);
      assert.equal(broadcasts.length, 0, "an all-replay batch must not be broadcast");
      const delivered = once(subscriber, "message", { signal: AbortSignal.timeout(3000) });
      await send(writer, request([oldMessage, freshMessage]));
      const [frame] = await delivered;
      assert.equal(frame.includes(Buffer.alloc(80, 3)), false);
      assert.equal(frame.includes(Buffer.alloc(17, 4)), true);
      assert.equal(db.prepare("SELECT COUNT(*) AS n FROM evolu_message").get().n, 1);
      assert.equal(db.prepare("SELECT storedBytes FROM evolu_usage").get().storedBytes, 17);
      assert.equal(db.prepare("SELECT COUNT(*) AS n FROM getbased_compacted_timestamp").get().n, 1);
    } finally { db.close(); }
  });
});

test("quota-rejected writes are neither persisted nor broadcast", async () => {
  await withRelay(async ({ connect }) => {
    const subscriber = await connect();
    await send(subscriber, request([], true));
    let broadcasts = 0;
    subscriber.on("message", () => broadcasts++);
    await send(await connect(), request([freshMessage]));
    await sleep(40);
    assert.equal(broadcasts, 0);
    const db = new Database("evolu-relay.db", { readonly: true });
    try { assert.equal(db.prepare("SELECT COUNT(*) AS n FROM evolu_message").get().n, 0); }
    finally { db.close(); }
  }, { isOwnerWithinQuota: () => false });
});

test("heartbeat terminates dead paths and keeps responsive sockets connected", async () => {
  await withRelay(async ({ connect }) => {
    const responsive = await connect();
    const dead = await connect({ autoPong: false });
    await once(dead, "close", { signal: AbortSignal.timeout(3000) });
    assert.equal(responsive.readyState, WebSocket.OPEN);
    await send(responsive, request());
  }, { pingInterval: "40ms" });
});

test("oversized frames close only their connection", async () => {
  await withRelay(async ({ connect }) => {
    const bad = await connect();
    const closed = once(bad, "close", { signal: AbortSignal.timeout(3000) });
    bad.send(Buffer.alloc(1024 * 1024 + 1));
    await closed;
    await send(await connect(), request([freshMessage]));
  });
});

test("broadcast backlog disconnects a client that stops reading", async () => {
  await withRelay(async ({ connect }) => {
    const subscriber = await connect();
    await send(subscriber, request([], true));
    subscriber._socket.pause();
    const writer = await connect();
    try {
      // Exceed the 16 MiB queue plus the OS send buffer using real sockets.
      // The writer reads every acknowledgment; only the subscriber is stalled.
      for (let counter = 0; counter < 100; counter++) {
        await send(writer, request([{
          timestamp: { millis: 3000, counter, nodeId: "0011223344556677" },
          change: Buffer.alloc(256 * 1024),
        }]));
      }
      const closed = once(subscriber, "close", { signal: AbortSignal.timeout(3000) });
      subscriber._socket.resume();
      await closed;
      assert.equal(writer.readyState, WebSocket.OPEN);
    } finally { subscriber._socket.resume(); }
  });
});
